### ISSUE TITLE
Error: Not Found

### ISSUE THREAD

**Issue by treiher** [brettcannon/check-for-changed-files#69]
I tried several configurations, but I always got just an `Error: Not Found`. It is not clear to me if the error message refers to the file pattern. All file patterns I tried led to the same result. Here is an example:

```yaml
on:
  pull_request:

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: brettcannon/check-for-changed-files@v1.1.0
        with:
          file-pattern: "CHANGELOG.md"
```

```
2022-05-20T13:32:54.1640282Z Download action repository 'brettcannon/check-for-changed-files@v1.1.0' (SHA:551263a821fde32615499b71f9283a7e98fcc657)
2022-05-20T13:32:55.2716598Z ##[group]Run brettcannon/check-for-changed-files@v1.1.0
2022-05-20T13:32:55.2717077Z with:
2022-05-20T13:32:55.2717355Z   file-pattern: CHANGELOG.md
2022-05-20T13:32:55.2717971Z   failure-message: the prerequisite file pattern ${prereq-pattern} matched changed files in the pull request, but the ${file-pattern} pattern did NOT and the ${skip-label} label is not set
2022-05-20T13:32:55.2718542Z ##[endgroup]
2022-05-20T13:32:55.7286957Z ##[error]Not Found
```

**Comment by brettcannon** [comment]
Do you have a GitHub Actions run you can point me at? The phrase "Not Found" is not from this repository, so I'm not sure what's causing that to appear in those logs. Maybe try `actions/checkout@v3`? You can see https://github.com/brettcannon/check-for-changed-files/blob/main/.github/workflows/pull-request.yml as a working example and https://github.com/brettcannon/check-for-changed-files/runs/6519302281?check_suite_focus=true#step:3:9 as what a failure is supposed to look like.

**Comment by treiher** [comment]
The problem occurs when the action is used in a private repository. In a public repository, the example workflow mentioned above works fine.

**Comment by brettcannon** [comment]
Huh, weird. Does your org allow for 3rd-party actions to be used? I wonder if somehow GitHub Actions is preventing the action from seeing your source code since it's in a private repository?

**Comment by treiher** [comment]
I am not aware of any explicitly configured restrictions. I was also able to reproduce the issue with a personal repository. As soon as I made the repository private, the action stopped working. Maybe GitHub Actions are restricted in general in private repositories? Maybe this is the reason why other actions require setting the `GITHUB_TOKEN` as environment variable (like [this](https://github.com/Zomzog/changelog-checker) one)?

**Comment by brettcannon** [comment]
Maybe https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository can help?

**Comment by brettcannon** [comment]
Closing as stale as I never heard back about the org-level repository settings.
