### ISSUE TITLE
Upgrade to node 16

### ISSUE THREAD

**Issue by brettcannon** [brettcannon/check-for-changed-files#75]
The node 12 runner is being deprecated.

**Comment by brettcannon** [comment]
Will require updating (at least):
1. https://github.com/brettcannon/check-for-changed-files/blob/main/tsconfig.json
2. https://github.com/brettcannon/check-for-changed-files/blob/main/action.yml
3. https://github.com/brettcannon/check-for-changed-files/blob/main/package.json
4. https://github.com/brettcannon/check-for-changed-files/blob/main/.github/workflows/pull-request.yml

**Comment by lukasoppermann** [comment]
Hey is there any progress on this? I am also getting the warning when using this action and would like to get it resolved. :D

**Comment by brettcannon** [comment]
https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsusing-for-javascript-actions to document that fact that there isn't a way to skip to Node 18.
